### ISSUE TITLE
InaSAFE User Map - Events

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/django-user-map#2]
# Problem

Desire to show user events on the a map
# Background

https://github.com/kartoza/flask_user_map/issues/5
# proposal
1. that event map and user map may not be the same thing. that the person visiting the site gets to choose what they can see; users, events or both.
2. that the OSM training tracking map http://openstreetmap.or.id/ushahidi/ contains much relevant information about training events. seek ways to share the same database with HOT.
   #cc
   @akbargumbira @iyan31 @timlinux

**Comment by akbargumbira** [comment]
@timlinux: so this is the ER diagram for implementing user and events:
![19agustus2014](https://cloud.githubusercontent.com/assets/992519/3964536/9d0f3db0-278a-11e4-97bc-e938a0455288.png)

Some notes from me:
- All new user and event will need to be approved by site administrator now. After registering user/event, it will mail the user that the record is on the list to be checked by admin. After site administrator approves the record, it will also mail the user saying the record is approved and inform the edit/delete link. Agree?
- Editing/deleting user/event will be available by using guid. This updated entry will go to unapproved entry for site administrator to re-check
- All the registered users are able to create event
- The  materials for an event will be put as text link in additional_info
- Should we add timezone information on the database for event? Since we want to grey out past event for the user so that we can check with the timezone from user's client (browser)

**Comment by timlinux** [comment]
Some comments:
- I think it is too much admin overhead to approve each user manually. Why not let them just self register and we approve event participants only.
- I would rather see user removed (django provides auth_user and extensible user_profiles) and rather think about participants (auth_user) where an event has many participants and each participant can be at many events. There would be an event_participants m2m relation established to support this.
- I know your model does not show it but in django the event component and the user map should be separate django apps.
- Event and user longitude and latitude fields should be respectively compined into a single location field of type  PointField (see https://docs.djangoproject.com/en/dev/ref/contrib/gis/model-api/#pointfield)
- event.number_participant -> event.participant_count
- id_participant_type -> participant_type_id (is this to restrict what type of participants are allowed? Should this not be a many to many relation to participant_type?)
- What is the id_registrant field for?
- FYI Django provides built in support for roles, no need to roll your own

**Comment by Charlotte-Morgan** [comment]
@akbargumbira - what is the status of this requirement?

**Comment by akbargumbira** [comment]
no progress. I need a clear requirement from how user inputs the events until it gets shown on the map (including how the validation of the events)

**Comment by akbargumbira** [comment]
@Charlotte-Morgan I made a repo for inasafe event map here https://github.com/AIFDR/inasafe-event-map. We should discuss about the detail of the requirements there.
