### ISSUE TITLE
Email old map users and ask them to re-add themselves to the new map

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/django-user-map#38]
As we already have 66 users registered at the moment, we need to migrate those registered users to the new system.

My suggestion is to:
1. Migrate all users to the new db with:
    - is_confirmed == true
    - is_admin == false
    - is_active = true
    - with random password
2. Mail all those users their random password and the link to set new password.

@timlinux: Any suggestion to do this? Thanks

**Comment by timlinux** [comment]
I suggest we just ask @mahardika to manually enter the users

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux & @akbargumbira 
-1 for getting @mahardika to do this manually.
The current user map says that users can be downloaded as *.csv but the file is not *.csv format.
I think we should have a simple download / upload option so that bulk loads can be done in future.
This way we could download, edit and upload a file rather than doing a manual edit.

What measures are in place to protect users email and phone details in the new user map?

**Comment by akbargumbira** [comment]
@Charlotte-Morgan, yeah, it's not using the standard separator. But in the new user map, it is using comma for the separator.

**Comment by timlinux** [comment]
Ok agreed we will do an automated import. We will use the dump from the backend database (which includes email etc.)

**Comment by Charlotte-Morgan** [comment]
see #57

**Comment by timlinux** [comment]
Migrated users should receive a notification asking them if they would like to update their details.

**Comment by timlinux** [comment]
Following sprint meeting on 7 Jan 2015 - we are going to update this task to simply email all existing users and ask them to re-add themselves to the new map.

**Comment by akbargumbira** [comment]
Hi @timlinux @Charlotte-Morgan @adissadis, I have made django management script to send the email. If it's ready, this is just a matter of pushing the button. I am waiting your command..

**Comment by akbargumbira** [comment]
done
